spring:
    application:
        name: gulimall-gateway
    cloud:
      gateway:
        routes:
          - id: route_baidu
            uri: https://www.baidu.com
            predicates:
              - Query=uri,baidu
          - id: route_qq
            uri: https://www.qq.com
            predicates:
              - Query=uri,qq
      nacos:
        server-addr: 192.168.43.47:8848
server:
  port: 80