spring:
  application:
    name: gulimall-gateway
  cloud:
    gateway:
      routes:
        - id: route_baidu
          uri: https://www.baidu.com
          predicates:
            - Query=uri,baidu
        - id: route_qq
          uri: https://www.qq.com
          predicates:
            - Query=uri,qq
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            #              - /renren-fast/ 因为配置了servlet.context-path=/renren-fast
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

    nacos:
      server-addr: 192.168.115.128:8848
server:
  port: 88
#  前端项目，/api
#  http://localhost:88/api/captcha.jpg  http://localhost:88/renren-fast/captcha.jpg